apiVersion: v1
kind: PersistentVolume
metadata:
  name: gopro-processor-storage
  labels:
    app.kubernetes.io/name: gopro-video-processor
    app.kubernetes.io/component: storage
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast-ssd
  hostPath:
    path: /mnt/gopro-storage
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gopro-processor-pvc
  namespace: gopro-processor
  labels:
    app.kubernetes.io/name: gopro-video-processor
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: fast-ssd
---